### ISSUE TITLE
Can we attach an array of tags when creating alert definition?

### ISSUE THREAD

**Issue by nischit7** [logzio/logzio_terraform_provider#35]
I am using this terraform provider for setting up alerts in logzio.
As per logzio API docs, when we create alert definitions, we can attach an array of "tags" to make it more searchable.
I looked at this specific terraform provider code base and the golang code which acts as logzio client, I did not see any reference to "tags" being supported.
Is that the case? If so, can this support be added?

**Comment by nischit7** [comment]
@jonboydell ... tagging you to get some attention

**Comment by yyyogev** [comment]
Done at https://github.com/logzio/logzio_terraform_provider/pull/43
