### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by svroonland** [logzio/logzio_terraform_provider#37]
Would be great to support adding tags to created alerts.

**Comment by jonboydell** [comment]
Note - from the swagger docs - https://github.com/logzio/public-api/blob/master/alerts/swagger.json - isn't in the example on the API page
```
"tags" : {
    "type" : "array",
    "items" : {
        "type" : "string"
     },
    "maxItems" : 10,
    "minItems" : 0
},
```

**Comment by yyyogev** [comment]
Done at https://github.com/logzio/logzio_terraform_provider/pull/43
