### ISSUE TITLE
Whitespace changes in the filter cause unnecessary resource updates

### ISSUE THREAD

**Issue by owenrumney** [logzio/logzio_terraform_provider#38]
Without any changes to the filter, terraform still looks to update the `logzio_alert` which in our case resets the alert and overrides the changes to the alert notification output format. (we change from JSON to table format which isn't possible to set through terraform at the moment)

It looks like the `DiffSuppressFunc` could be used to prevent this.

**Comment by yyyogev** [comment]
done at https://github.com/logzio/logzio_terraform_provider/pull/43
